NULL_PAGE_ID = -1
META_PAGE_ID = 0

BYTES_PAGE = 4096
BYTES_MAGIC_NUMBER = 2
BYTES_USED_PAGE_ID = 4
BYTES_HEAD_PAGE_ID = 4
BYTES_TAIL_PAGE_ID = 4
BYTES_TABLE_SEQ = 4
BYTES_TABLE_HEAD_PAGE_ID = 4
BYTES_TABLE_TAIL_PAGE_ID = 4
BYTES_ROOT_PAGE_ID = 4

DEGREE = 2

MAGIC_NUMBER_BS = b'\x95\x27'

NUM_PAGE_IDS = 2

NUM_TABLE = 2