NULL_PAGE_ID = -1
META_PAGE_ID = 0

BYTES_PAGE = 4096
BYTES_MAGIC_NUMBER = 2
BYTES_USED_PAGE_ID = 8
BYTES_HEAD_PAGE_ID = 8
BYTES_TAIL_PAGE_ID = 8
BYTES_B_PLUS_TREE_SEQ = 8
BYTES_TABLE_HEAD_PAGE_ID = 8
BYTES_TABLE_TAIL_PAGE_ID = 8
BYTES_ROOT_PAGE_ID = 8

DEGREE = 2

MAGIC_NUMBER_BS = b'\x95\x27'

NUM_PAGE_IDS = 2

NUM_TABLE = 2

INIT_B_PLUS_TREE_SEQ = 0